### PR TITLE
Inject callables using humilis lambda reference

### PR DESCRIPTION
**Pull request by germangh**
Templating the `requirements.txt` of the Lambda function as is done in master doesn't work as expected. The reason is that local lambda dependencies need to be installed and packaged by humilis so humilis needs to be able to find those local dependencies. This would require the user to use absolute paths in the `lambda_dependencies`. In this PR the dependencies in `lambda_dependencies` are all relative to the location of the environment definition file. An additional advantage of using humilis is that you have more flexibility as to how you express your Lambda dependencies and that a `setup.py` is not needed when a local package is completely self-contained. All below are valid:

```
# All local paths are relative to the location of the environment definition file
# This directory contains a __init__.py file
- path/to/local/pkg/dir/
# A completely self-contained local module. Handy for very simple callables.
- path/to/local/module.py
# Path to a local "pip installable". This path contains a setup.py file
- path/to/local/pip/installable/
# Path to a local requirements file
- path/to/requirements.txt
# A Pypi dependency
- pyyaml
# A private index dependency
- http://pypi.fih.io/data/pypi/+simple/:privatepackage
```

Apart from that some minor fixes that were preventing a successful deployment by travis (e.g. pdbb was breaking the deployment, and didn't care to investigate further since it's not a good idea to install in travis anything else than what is needed for deployment/testing).

---
This change is [Reviewable](https://reviewable.io/reviews/humilis/humilis-kinesis-mapper/1)

### CODE REVIEW

**Comment by bubenkoff** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[humilis_kinesis_mapper/meta.yaml.j2, line 17 \[r1\]](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1#-KEHdM8V2CVOCZUHfQUQ:-KEHdM8WifIiaHbiai05:-1465295961) ([raw file](https://github.com/humilis/humilis-kinesis-mapper/blob/b516eec3cb9bc94c867b1755f30e77707571c399/humilis_kinesis_mapper/meta.yaml.j2#L17)):*
not sure why is it removed? it's a parameter of the layer

---

*[tests/integration/mycode/myparserpkg/__init__.py, line 1 \[r1\]](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1#-KEHds3z5ZAOz_bzvuF8:-KEHds4-ZasBdqexctQ2:986290750) ([raw file](https://github.com/humilis/humilis-kinesis-mapper/blob/0552554e3301c22a9ff65243367df02477194f63/tests/integration/mycode/myparserpkg/__init__.py#L1)):*
no need in utf-8 encoding

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1)*

**Comment by germangh** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[humilis_kinesis_mapper/meta.yaml.j2, line 17 \[r1\]](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1#-KEHdM8V2CVOCZUHfQUQ:-KEHeO_KiZ3xVbcfRvo4:42288822) ([raw file](https://github.com/humilis/humilis-kinesis-mapper/blob/b516eec3cb9bc94c867b1755f30e77707571c399/humilis_kinesis_mapper/meta.yaml.j2#L17)):*
I removed it because it serves no purpose (the lambda_dependencies template param is used in the lambda ref only). But I see that it makes sense to leave that part there just to document the layer interface. I'll put it back.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1)*

**Comment by bubenkoff** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[humilis_kinesis_mapper/meta.yaml.j2, line 17 \[r1\]](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1#-KEHdM8V2CVOCZUHfQUQ:-KEOHL1tCcUzx8ZNVrZq:371876914) ([raw file](https://github.com/humilis/humilis-kinesis-mapper/blob/b516eec3cb9bc94c867b1755f30e77707571c399/humilis_kinesis_mapper/meta.yaml.j2#L17)):*
as discussed, lambda_dependencies param is also used in requirements.txt of the lambda package 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1)*

**Comment by germangh** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[humilis_kinesis_mapper/meta.yaml.j2, line 17 \[r1\]](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1#-KEHdM8V2CVOCZUHfQUQ:-KEOHh1xeqNFM39-BIc0:-2027412344) ([raw file](https://github.com/humilis/humilis-kinesis-mapper/blob/b516eec3cb9bc94c867b1755f30e77707571c399/humilis_kinesis_mapper/meta.yaml.j2#L17)):*
I deleted the requirements.txt of the lambda package because it's not necessary/used in this version. In the current version of humilis the "lambda" reference parser installs the lambda_dependencies after resolving their absolute paths. Then it also installs the requirements.txt, if it exists. So there is no need of having the same list of dependencies (even if the paths in the requirements.txt would be absolute) in the requirements.txt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1)*

**Comment by bubenkoff** [comment]
Reviewed 15 of 17 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-kinesis-mapper/1)*

**Comment by bubenkoff** [comment]
tests are failing now

**Comment by germangh** [comment]
Apparently we are using Samuel's credentials to run tests?
https://www.dropbox.com/s/oipd0qbwcf78eof/Screenshot%202016-04-03%2002.49.01.png?dl=0

I removed the admin privileges to that user so that explains why the deployment fails now.

**Comment by bubenkoff** [comment]
cool!

**Pull request merged**
